<?php


namespace Security\HTMLPurifier;

class HTMLPurifier_Default_config
{
    public static $config = array("Core.LexerImpl" => null,
        "Core.MaintainLineNumbers" => null,
        "Output.CommentScriptContents" => true,
        "Output.FixInnerHTML" => true,
        "Output.SortAttr" => false,
        "Output.FlashCompat" => false,
        "Cache.DefinitionImpl" => null,
        "HTML.DefinitionRev" => 1,
        "Cache.SerializerPath" => null,
        "Cache.SerializerPermissions" => 493,
        "HTML.Trusted" => false,
        "HTML.Doctype" => null,
        "HTML.CustomDoctype" => null,
        "HTML.XHTML" => true,
        "HTML.Strict" => false,
        "HTML.AllowedModules" => null,
        "HTML.CoreModules" => array(
            "Structure" => true,
            "Text" => true,
            "Hypertext" => true,
            "List" => true,
            "NonXMLCommonAttributes" => true,
            "XMLCommonAttributes" => true,
            "CommonAttributes" => true,
        ),
        "HTML.SafeObject" => false,
        "HTML.SafeEmbed" => false,
        "HTML.SafeScripting" => array(),
        "HTML.Nofollow" => false,
        "HTML.TargetBlank" => false,
        "HTML.TargetNoreferrer" => true,
        "HTML.TargetNoopener" => true,
        "HTML.MaxImgLength" => 1200,
        "HTML.Attr.Name.UseCDATA" => false,
        "HTML.SafeIframe" => false,
        "HTML.TidyLevel" => "medium",
        "HTML.TidyAdd" => array(),
        "HTML.TidyRemove" => array(),
        "HTML.BlockWrapper" => "p",
        "HTML.Parent" => "div",
        "HTML.AllowedElements" => null,
        "HTML.AllowedAttributes" => null,
        "HTML.Allowed" => null,
        "HTML.ForbiddenElements" => array(),
        "HTML.ForbiddenAttributes" => array(),
        "Attr.IDBlacklist" => array(),
        "Core.Encoding" => "utf-8",
        "Core.NormalizeNewlines" => true,
        "Core.ConvertDocumentToFragment" => true,
        "Core.LegacyEntityDecoder" => false,
        "Core.RemoveProcessingInstructions" => false,
        "Core.HiddenElements" => array(
            "script" => true,
            "style" => true,
        ),
        "Core.AggressivelyRemoveScript" => true,
        "Core.RemoveScriptContents" => null,
        "Core.AggressivelyFixLt" => true,
        "Core.EscapeInvalidTags" => false,
        "Core.RemoveInvalidImg" => true,
        "HTML.AllowedComments" => array(),
        "HTML.AllowedCommentsRegexp" => null,
        "Core.DisableExcludes" => false,
        "Core.EscapeNonASCIICharacters" => false,
        "HTML.Proprietary" => false,
        "Filter.Custom" => array(),
        "Attr.DefaultImageAlt" => null,
        "URI.Disable" => false,
        "URI.DefinitionRev" => 1,
        "URI.Host" => null,
        "URI.Base" => null,
        "URI.DefaultScheme" => "http",
        "URI.DisableExternal" => false,
        "URI.DisableExternalResources" => false,
        "URI.DisableResources" => false,
        "URI.HostBlacklist" => array(),
        "URI.SafeIframeRegexp" => null,
        "URI.MakeAbsolute" => false,
        "URI.Munge" => null,
        "URI.AllowedSchemes" => array(
            "http" => true,
            "https" => true,
            "mailto" => true,
            "ftp" => true

        ),
        "URI.OverrideAllowedSchemes" => true,
        "AutoFormat.AutoParagraph" => false,
        "Output.TidyFormat" => false,
        "Output.Newline" => null,
        "AutoFormat.Custom" => array()
    );

}

